### ISSUE TITLE
Error running example after setting up

### ISSUE THREAD

**Issue by LaTortueSolitaire** [UWGlaciology/CommunityFirnModel#13]
Hi,

I set up the repo on my computer and tried to run the main.py file with the example.json but got this error:

`Traceback (most recent call last):
  File "C:\Users\xxxx\Documents\perso_work\CommunityFirnModel\CFM_main\main.py", line 84, in <module>
    firn = FirnDensityNoSpin(configName, climateTS = climateTS, NewSpin = NewSpin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\Documents\perso_work\CommunityFirnModel\CFM_main\firn_density_nospin.py", line 466, in __init__
    self.sublimSec  = self.sublim / S_PER_YEAR / (S_PER_YEAR/self.dt) # sublimation at each time step (meters i.e. per second). gets multiplied by S_PER_YEAR later. (sort of hacky, I know)
                      ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (6827,) (6828,) `

I am not sure what the issue is. 
I installed all the requirements ( in requirement file, missing psutil, that was required to run the example).

Thank you for your assistance.

**Comment by maximusjstevens** [comment]
Hi @LaTortueSolitaire,

Apologies for the delay fixing this - I was on leave the last month. There was a bug in setting up the time-stepping vectors. If you pull the latest version (2.3.2) it should be fixed. Please open a new ticket if not!
