### ISSUE TITLE
Include example CSV files?

### ISSUE THREAD

**Issue by vonw** [UWGlaciology/CommunityFirnModel#5]
Would it be possible to include the example CSV files in CFMinput? The pkl file of MERRA data (MERRA2_CLIM_df_72.5_-38.75.pkl) is there, but the following CSV files (that are required for the example run) are not.

"InputFileFolder": "CFMinput",
"InputFileNameTemp": "example_tskin.csv",
"InputFileNamebdot": "example_smb.csv",
"InputFileNameIso": "example_isotope.csv",
"InputFileNamerho": "example_rhos.csv",
"InputFileNamemelt": "example_melt.csv",
"initfirnFile": "example_firndata.csv",

This would make it very easy for a newbie (like myself) to clone the CFM and run the example case using example.json. It would also provide a starting place to start creating one's own input files.

**Comment by maximusjstevens** [comment]
Good suggestion - I will include these in the next release.
